repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
        args:
          - --unsafe
      - id: check-symlinks
      - id: check-added-large-files
      - id: detect-private-key

- repo: https://github.com/antonbabenko/pre-commit-terraform.git
  rev: v1.77.0
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
      args:
        - '--args=--config=.config/terraform-docs.yml'
    - id: terraform_validate
    - id: terraform_tflint
      args:
        - '--args=--config=.config/tflint.hcl'
        - --env-vars=TFLINT_LOG="info"
    - id: terraform_tfsec
